[FIX] new test file received
LevelPrime/l10n-italy pull request #6
Opened 2019-10-09 15:23 UTC by sergiocorato

2019-10-11 05:37 UTC, eLBati commented
Ma quindi il fornitore qui quanto vuole essere pagato?

2019-10-11 06:15 UTC, sergiocorato commented
4.09

2019-10-11 07:25 UTC, eLBati commented
Però allora non sappiamo che significato abbia `<Arrotondamento>-0.30</Arrotondamento>`. Cioè non sappiamo cosa c'era nella testa di chi ha prodotto quell'XML quando ha scritto quel campo.

In questo caso, se il fornitore vuole essere pagato 4,09, l'XML sembra proprio sbagliato.
E se odoo importasse un totale di 3,79 non me la sentirei di dargli torto.

2019-10-11 07:47 UTC, sergiocorato commented
si, non ha molto senso la fattura, però direi che la modifica aggiunta è un controllo di coerenza che non dovrebbe fare alcun male (gli altri test vanno tutti bene) quindi rendiamo la funzione più 'furba' :D

2019-10-11 09:23 UTC, eLBati commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                tot_doc - rounding + vat - tot_doc_computed,
@sergiocorato mi spieghi questa riga?

2019-10-14 16:17 UTC, robyf70 requested changes
Penso che potremmo effettivamente utilizzare una logica del genere, però magari proporrei di notificare la situazione all'utente

2019-10-14 16:17 UTC, robyf70 commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                tot_doc - rounding + vat - tot_doc_computed,
@eLBati praticamente calcola il vero scostamento sull'arrotondamento indicato sulla fattura

2019-10-14 16:21 UTC, robyf70 commented
@sergiocorato @eLBati  spostiamo PR e discussione in l10n_italy?

2019-10-15 08:47 UTC, eLBati commented
:+1:

2019-10-15 12:42 UTC, sergiocorato commented
:+1:

2019-10-15 12:43 UTC, sergiocorato commented on l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
> +                tot_doc - rounding + vat - tot_doc_computed,
esatto

2019-10-16 08:08 UTC, sergiocorato commented
faccio PR a sè

2019-10-16 08:08 UTC, closed without merging

2019-10-18 13:06 UTC, sergiocorato commented
spostato in #1500